name: Docker Image Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

    paths-ignore:
      - 'docs/**'
      - '.devcontainer/**'
      - '**.md'

    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      # copy the secrets to env vars for if: conditions

      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}

      TENANT: ${{ secrets.TENANT }}
      SERVICE_PRINCIPAL: ${{ secrets.SERVICE_PRINCIPAL }}

      ACR_REG: ${{ secrets.ACR_REG }}
      ACR_REPO: ${{ secrets.ACR_REPO }}
      ACR_IMAGE: ${{ secrets.ACR_IMAGE }}

      KEYVAULT_NAME: ${{ secrets.KEYVAULT_NAME }}
      AUTH_TYPE: CLI

      AZURE_SET: false
      DOCKER_SET: false
      ACR_SET: false

    steps:
    - uses: actions/checkout@v1

    - name: Set conditions
      run: |
        DOCKER_PAT=${{ secrets.DOCKER_PAT }}
        SERVICE_PRINCIPAL_SECRET=${{ secrets.SERVICE_PRINCIPAL_SECRET }}

        echo "::set-env name=AZURE_SET::${{ env.SERVICE_PRINCIPAL_SECRET != '' && env.TENANT != '' && env.SERVICE_PRINCIPAL != '' && env.KEYVAULT_NAME != '' }}"
        echo "::set-env name=DOCKER_SET::$DOCKER_PAT != '' && $DOCKER_REPO != '' && $DOCKER_USER != ''"
        echo "::set-env name=ACR_SET::${{ env.ACR_REG != '' && env.ACR_REPO != '' && env.ACR_IMAGE !='' }}"

        echo $SERVICE_PRINCIPAL_SECRET
        echo $ACR_SET
        
        echo $DOCKER_PAT
        echo $DOCKER_SET

        # temp test
        echo "::set-env name=DOCKER_SET::false"
        echo "::set-env name=ACR_SET::false"
        
        #echo "::set-env name=SERVICE_PRINCIPAL_SECRET::''"
        #echo "::set-env name=DOCKER_PAT::''"

    - name: Test Check
      run: |
        echo $SERVICE_PRINCIPAL_SECRET
        echo $ACR_SET
        
        echo $DOCKER_PAT
        echo $DOCKER_SET

    - name: Validate Azure Access
      if: ${{ env.AZURE_SET == 'true' }}
      run: |
        # login to Azure
        az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL }} --tenant ${{ secrets.TENANT }} -p ${{ secrets.SERVICE_PRINCIPAL_SECRET }}

        # verify SP has access to Key Vault
        az keyvault secret show --name CosmosDatabase --vault-name $KEYVAULT_NAME

    - name: Docker Login
      if: ${{ env.DOCKER_SET == 'true' }}
      run: |
        # login to dockerhub
        echo "${{ secrets.DOCKER_PAT }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Docker Pull Test
      if: ${{ env.AZURE_SET == 'true' || env.DOCKER_SET == 'true' || env.ACR_SET == 'true' }}
      run: |
        # Pull the latest image if needed
        # This doesn't have to be a separate step, but makes the output easier to read and debug
        docker pull mcr.microsoft.com/dotnet/core/sdk:3.1

    - name: Docker Build Test
      if: ${{ env.AZURE_SET == 'true' }}
      run: |
        # build test image
        docker build . -t test --target test

    - name: Install WebV
      if: ${{ env.AZURE_SET == 'true' }}
      run: |
        dotnet tool install -g webvalidate

    - name: Start helium container
      if: ${{ env.AZURE_SET == 'true' }}
      run: |
        # run the app
        docker run -d --name hcs -p 4120:4120 --env KEYVAULT_NAME=$KEYVAULT_NAME --env AUTH_TYPE=$AUTH_TYPE -v ~/.azure:/root/.azure test
        
        docker logs hcs --tail 30

        echo "Waiting for web server to start and run initial tests ..."
        sleep 25

    - name: Run WebV
      if: ${{ env.AZURE_SET == 'true' }}
      run: |
        # run web validation test
        # fail on any validation errors
        webv -s localhost:4120 --max-errors 0 -f e2e.json

    - name: Display coverage results
      if: ${{ env.AZURE_SET == 'true' }}
      run: |
        # wait for helium to shutdown
        sleep 15

        # display the results
        docker logs hcs | tail -n 24

    - name: Display full test results
      if: ${{ env.AZURE_SET == 'true' }}
      run: |
        # display the results
        docker logs hcs

    - name: Docker Pull Release
      if: ${{ env.DOCKER_SET == 'true' || env.ACR_SET == 'true' }}
      run: |
        # Pull the latest image if needed
        docker pull mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine

    - name: Docker Build Release
      if: ${{ env.DOCKER_SET == 'true' || env.ACR_SET == 'true' }}
      run: |
        # build release image
        docker build . -t helium

    - name: Docker Tag and Push
      if: ${{ env.DOCKER_SET == 'true' }}
      run: |
        # tag the repo with :beta
        docker tag helium $DOCKER_REPO:beta

        # Tag image based on repo tag if a github label
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]
        then

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,'  | sed -e 's/^v//')

          # tag the image with :version and :stable
          docker tag helium $DOCKER_REPO:$VERSION
          docker tag helium $DOCKER_REPO:stable
        fi

        # Push to the repo
        docker push $DOCKER_REPO
    
    - name: ACR Push
      if: ${{ env.ACR_SET == 'true' && env.AZURE_SET == 'true' }}
      run: |
        # login to acr
        az acr login -n $ACR_REG

        # build the complete image name
        ACR_IMAGE=$ACR_REG.azurecr.io/$ACR_REPO/$ACR_IMAGE

        # build release image
        docker tag helium $ACR_IMAGE:beta

        # Tag image based on repo tag if a github label
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]
        then

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
          # Strip "v" prefix from tag name
          VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          # tag the image with :version and :stable
          docker tag helium $ACR_IMAGE:$VERSION
          docker tag helium $ACR_IMAGE:stable
        fi
        
        # push the repo
        docker push $ACR_IMAGE
