name: DockerCI-PR

on:
  pull_request:
    branches:
      - master

    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'saveenv.sh'

jobs:

  docker-build-push:

    runs-on: ubuntu-latest
    env:
      #  DOCKER_REPO  - the docker repository name in the form: organization/repository
      DOCKER_REPO: 'retaildevcrew/helium-csharp'

    steps:
    - uses: actions/checkout@v1

    - name: Login to registry
      run: |
        # Login to registry

        #    You must add the following secrets to github
        #    DOCKER_USER  - your dockerhub user name
        #    DOCKER_PAT   - the personal access token for dockerhub
       

        ## login to dockerhub
        echo "${{ secrets.DOCKER_PAT }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Build Container
      run: |
        # testing az
        echo $PATH
        
        az login --service-principal  -u http://helium-githubci -p ${{ secrets.DOCKER_PAT }} --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47
        az account show -o table
        az account get-access-token --output json --resource https://vault.azure.net
