name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag helium-csharp:stable
    - name: Docker Publish
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        # Name of the Docker image
        name: retaildevcrew/helium-csharp
        # Tag for the Docker image
        tag: stable
        # Script body to compute tag name for the Docker image, has context as the main function argument
        # tag script: # optional
        # Username for Docker registry
        username: ${{ secrets.DOCKER_USER }}
        # Password for Docker registry
        password: ${{ secrets.DOCKER_PAT }}
        # Registry URL
        registry: hub.docker.com
        # Don't skip pull requests
        #include pull requests: # optional
